//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduInstitutesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Pharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy()
        {
            this.ServicePharmacies = new HashSet<ServicePharmacy>();
        }
    
        public int PharmacyId { get; set; }
        public string PharmacyName { get; set; }
        public string Info { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Site { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Photo { get; set; }
        public int CategoryId { get; set; }
        public int WorkTimeId { get; set; }
        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Photo.Trim();
            }
        }

        public virtual Category Category { get; set; }
        public virtual WorkTime WorkTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePharmacy> ServicePharmacies { get; set; }
    }
}
